### ISSUE TITLE
@RouteScoped beans are not discovered when bean-discovery-mode="annotated"

### ISSUE THREAD

**Issue by roeltje25** [vaadin/cdi#303] opened 2019-11-21 10:18 UTC
When using bean-discovery-mode="annotated" all beans with Pseudo-scopes are not discovered or considered as beans. In order to mitigate this RouteScoped would have to be a Stereotype for example. This is e.g. discussed in https://issues.jboss.org/browse/WELD-1733?_sscc=t

```java
@Stereotype
@Scope
@Inherited
@Target({ ElementType.ANNOTATION_TYPE, ElementType.TYPE, ElementType.FIELD,
        ElementType.METHOD, ElementType.CONSTRUCTOR })
@Retention(RetentionPolicy.RUNTIME)
public @interface RouteScoped {
}
```

**Comment by mehdi-vaadin** [comment] 2019-12-02 14:35
@roeltje25 thank you for reporting this. It seems that the problem is not solved by just adding `@Stereotype`. It needs investigation.

**Comment by roeltje25** [comment] 2019-12-03 15:33
Are you sure? For me that actually solves it. I am running on wildlfy 17

**Comment by mehdi-vaadin** [comment] 2019-12-03 15:40
Maybe I made a mistake. What exactly did you do? Only adding the `@Stereotype` to `RouteScoped`?

**Comment by roeltje25** [comment] 2019-12-06 08:28
Yep, that's all. Also for UISCoped by te way.

**Comment by roeltje25** [comment] 2020-02-04 06:25
*bump*

**Comment by roeltje25** [comment] 2020-04-09 13:35
still *bump*

**Comment by roeltje25** [comment] 2021-06-16 07:59
I have @RouteScoped and @UISCoped overridden in my projects already from 2019 to add the @StereoType annotation to make vaadin work with CDI and bean-discovery-mode="annotated".

Is there any reason to not fix this? Can I provide any assistance in getting this done?

**Comment by roeltje25** [comment] 2021-08-13 10:30
Again, I bump on this issue still.

I would like to refer to the CDI 1.2 spec that unless a pseudoscope is marked by @Stereotype it is not a bean-defining annotation. As such, this clearly is a bug. Please refer to the spec at: https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_defining_annotations

Is there anyone keeping an eye on this?

**Comment by roeltje25** [comment] 2021-09-21 07:28
sorry for being adamant and persevering... but:
*bump*

**Comment by roeltje25** [comment] 2022-02-23 10:26
Again a Bump here.... I still have to fix this in my project by overriding the Routescoped and UISCoped annotations.

Really nobody cares about this?

**Comment by taefi** [comment] 2022-08-23 10:39
@roeltje25 thanks for reporting this issue and being patient at the same time. 
I tried to do the same as you mentioned locally, which is:
- patching the vaadin-cdi to add `@Stereotype` on `@RouteScoped` definition,
- use the patched vaadin-cdi in the starter project
and the result is:
The beans annotated with `@RouteScoped` is always discovered when `bean-discovery-mode="all"` and it doesn't work no matter whether I use the above patch or not when `bean-discovery-mode="annotated"`. By "it doesn't work" I mean there is no error anywhere (not in the console and not in browser's console), but the view is loaded as a white blank page. the cdi-skeleton-starter is using the `wildfly-maven-plugin:3.0.0.Final` which I believe is launching the wildfly `17.0.1`.  

Would you be able to demonstrate what you can achieve by adding the `@Stereotype` in a minimal reproducible example project?

**Comment by roeltje25** [comment] 2022-08-24 09:07
> Would you be able to demonstrate what you can achieve by adding the `@Stereotype` in a minimal reproducible example project?

Will craft an example today.

**Comment by roeltje25** [comment] 2022-08-24 10:13
I have forked the cdi starter and made the MainView RouteScoped and for demo purposes also the GreetService UIScoped. That's a better demo because the @VaadinSessionScoped annotation is a NormalScope and discoverable anyway:
https://github.com/roeltje25/vaadin-cdi-issue-303-skeleton-starter-demo

Note that I am not certain how to use the adjusted cdi as a dependency in maven. Therefore I have manually added the two annotations in the project and made them stereotypes. (project sources override library sources). You will notice that everything works. If you remove the two overridden Scope annotations, it does not work anymore.

#Note
Interestingly, for me wildfly 26.1.1 is used (which seems to make more sense than 17.0.1). Why you got 17.0.1 is a bit puzzling to me.

**Comment by taefi** [comment] 2022-08-30 14:23
@roeltje25 thanks for taking the time to create the demo application. 
Before we accept and merge #392 I had some questions which possibly can be discussed. 

As mentioned in the https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_defining_annotations marking a pseudo-scope annotation such as `@Routescoped` or `@UIScoped` would make them **bean defining annotation**, and as the result, they (any available view and component class in the application) would be scanned as well while `bean-discovery-mode="annotated"`, and this kinda reminds me a behavior very similar to what we can achieve with `bean-discovery-mode="all"`. Do you have specific considerations regarding the use of `bean-discovery-mode="annotated"` in your application? This can shed some light on the decision we should make about marking those annotations as Stereotypes.

**Comment by roeltje25** [comment] 2022-08-31 08:10
Hi Taefi,

Most certainly. There are actually many classes in our code base that I absolutely do not wat to be considered as beans. Many utility classes for example. Some of those classes will actually give trouble during deployment of our app. Moreover, the deployment process will take a lot more time when bean-discovery-mode="all" is used. bean-discovery-mode="annotated" gives as precise control over which classes are beans AND gives us higher deployment speed. Especially when deploying many times in environments using docker containers deployment speed is key.

Apart from that this discussing is a bit of a red herring isn't it? The spec of CDI allows for the discovery mode "annotated" and Vaadin CDI does not support this -> this should be something we should fix in any case, right?

thanks for the followup!

**Comment by taefi** [comment] 2022-08-31 11:58
@roeltje25 Thanks for providing the context. Of course, this should be fixed somehow, but maybe/maybe not adding @Stereotype is the answer.

**Comment by roeltje25** [comment] 2022-09-01 09:42
@taefi 
Well according to the standard in annotated mode bean defining annotations are 
1. Annotations with @NormalScope
2. Annotations with @Stereotype
3. Annotations @interceptor and @Decorator
4. @Dependent annotation

Option 1 is not an option because components cannot be @normalScope as mentioned in javadoc of e.g. @NormalRouteScoped here : https://github.com/vaadin/cdi/blob/master/vaadin-cdi/src/main/java/com/vaadin/cdi/annotation/NormalRouteScoped.java
Option 3 is not applicable as we are looking at normal  beans not an interceptor
Option 4 is not applicable as the beans in question are not dependent. We would get multiple instances e.g. when injecting in several other beans.
It seems we should consider option 2 somehow.

One way is as proposed, adjust the vaadin pseudo scopes.
Another way would be to define, or force developers to define their own stereotype which contains the @RouteScoped annotation.
The latter solution sounds a bit verbose and 'feels' a bit like: we shove of the issue back to the devs...

Another solution still would be to somehow make the current annotation work as is by adjusting the vaadin cdi extension. However, as the annotations are not bean defining, I think finding the available beans would involve custom logic scanning the classes. This sounds to me overkill, and it's not very elegant to work around the standard this way.


My educated advice would really be to make the RouteScoped annotation a @Stereotype. Or if for some reason this absolutely is unacceptable at least provide a prewritten stereotype that already includes @RouteScoped. But again, while considering that, you already see thats a bit strange. You get 2 annotations that work the same, the only difference is that one of them won't work in discovery mode "annotated".

I rest my case...

**Comment by taefi** [comment] 2022-09-05 07:45
@roeltje25 again, thanks, for helping with this issue, it is really appreciated.

Actually, the reason that we are still looking into it slowly and closely is that we are concerned about those applications that for some reasons (such as startup performance, etc.) might not want to get all of their `@RouteScoped` and `@UIScoped` beans discovered at startup while they set `bean-discovery-mode="annotated"`. Probably, if from the beginning they were defined as `@Stereotype`s it was a different story. On one hand, adding `@StereoType` to `@RouteScoped` and `@UIScoped` would change this behavior, and on the other, adding one more set of annotations just for this purpose might be overkill IMO. In the end, we might consider adding `@StereoType` to those annotations as you suggested.

**Comment by roeltje25** [comment] 2022-09-05 08:15
I understand. Indeed if there are applications that work based on the
non-bean discovered operation of these annotations I would agree. But isn't
that just the whole point? under bean discovery mode "annotated" there
actually is no use of those annotations at all if they are not stereo
types. Well, unless:
1) these beans are interceptors or decorators... but I can not easily see
what would be the use case of a @Routescoped or @UIScoped interceptor. This
may be a valid boundary case though.
2) these beans have another @NormalScope as annotation. but why would you
annotate a bean with a normal scope AND with @RouteScoped or @UIScoped?
This is clearly an error on the dev's part if it exists in some codebase
3) these beans have a separate stereotype associated that makes them beans.
But in that case it doesn't matter if the @RouteScoped and @UIScoped
annotations become stereo types as well.
4) these beans are explicitly used as a set of beans that are enabled in
discovery mode "all" and not in mode "annotated, an switching between these
modes is used as a switch to enable these beans.... but this really is a
big no no on the dev's part. One should not overload a switch like the
discovery mode to implement some business or deployment logic.

Taking that into account I think that when you think about it, this simply
becomes a no-brainer....

Roel

P.S. This is not to sound pushy, but I have thought about this particular
issue already a long time...


--------------------------------------------
Roel Meeuws
Email: ***@***.***
Mob. phone: +31 (0)6 10 82 44 01
--------------------------------------------


[image: width=]
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op ma 5 sep. 2022 om 09:45 schreef Soroosh Taefi ***@***.***>:

**Closed** 2022-09-12 09:41 UTC
Labels: bug, Impact: Low, Severity: Major
