### ISSUE TITLE
CDI is broken

### ISSUE THREAD

**Issue by pleku** [vaadin/cdi#286] opened 2019-04-17 11:31 UTC
Checkout branch `flow-2` and the `CdiInstantiator` will be broken due to missing `createComponent(T method)` method. 

Not directly related to Flow `2.0` or `npm` but this change https://github.com/vaadin/flow/commit/154a56e4d400d94f6ec2466f988cfeabab6c5296

**Comment by kumm** [comment] 2019-04-20 19:56
CDI instantiation for `@id` is a documented feature in CDI addon according to https://vaadin.com/docs/v13/flow/cdi/tutorial-cdi-instantiated-beans.html.
It tries to warn about the strange behaviour by saying "A dependent bean is safe". 
Dependent beans work like beans created by `createComponent(T method)` in Spring addon (as of https://github.com/vaadin/spring/commit/16787030ea41a9e10c9049e255cc5df5f219ebbc).

To exactly work like Spring addon would mean to always instantiate the bean regardless of its scope. I don't like it, because violates the whole concept of contexts.

It should be decided what is the point. Some ideas:
- fix it, and leave current behaviour as is
- force dependent scope in `createComponent(T method)`
- work exactly like spring addon

**Comment by denis-anisimov** [comment] 2019-04-23 13:17
I vote for 
`force dependent scope in createComponent(T method)`.
The current behavior is wrong. It causes the bug https://github.com/vaadin/flow/issues/4634.
The semantic of the `createComponent` which is used for `@Id` case is `create` not `create or get`.
If you look at the impl then you will see that an `Element` is created for the injected component and then it's wrapped by an appropriate component which should not be already initialized by another `Element` .
And an existing component (stored in some scope) will be already initialized with some element. This is wrong.
In fact, effectively the second and the third case are the same. Sine a template keeps a reference to 
the injected element then the injected instance is always associated with the template instance so it dependent semantically already.

**Comment by denis-anisimov** [comment] 2019-04-23 13:49
I'm trying to figure out how to specify the scope for a `Bean` (or create a new Bean for the existing one with a new scope) but don't see a way.
Could you please let me know a way if you know it?

**Comment by kumm** [comment] 2019-04-23 19:54
More or less ( ok, less)  the mentioned documentation tries to explain the problem with element binding.

To only avoid the reported bug https://github.com/vaadin/flow/issues/4634 you should use `@Typed(MyCustomDialog.class)` annotation on `MyCustomDialog`. It means a bean of class  `MyCustomDialog` will be injected only for `MyCustomDialog`. In fact it is the safe way with dependency injection in the case of extending an other Vaadin component. Though it does not solve element binding problems with polymer template.

At `force dependent scope` I mean to check the scope in `createComponent`, and throw an exception for other scopes. This way it is really different, and really dumb, but does not force CDI to ignore contexts.

There are few ways to manually create a bean instance as a non-contextual instance. You can find a good summary here http://www.next-presso.com/2017/06/non-contextual-instances-in-cdi/. As you can see it is not so simple as with Spring. 
Use Case 1 with `Unmanaged` should be the way in this case. Since we are not able to determine when to execute step 5, and 6 (preDestroy, and dispose) some experiment is needed to see the impact of omitting these. Side note: because of the same reason dependent beans also suffer omitted destroy.

**Comment by denis-anisimov** [comment] 2019-04-24 06:06
>To only avoid the reported bug vaadin/flow#4634 you should use @Typed(MyCustomDialog.class) annotation on MyCustomDialog. It means a bean of class MyCustomDialog will be injected only for MyCustomDialog.

This is a workaround I would say.
The issue is still genuine: `createComponent` semantic has to be `create` and never `get`.
Just because it's the requirement of the implementation.

The usecase can be modified easily to use the same type (the type is not a cause of the issue at all).
Also it may be that I have several subclasses of `Dialog` which are injected by their own type. In that case `createComponent`  will throw but it should not.
Also : why should I care about this issue in `MyCustomDialog` class which is a totally isolated from this functionality? It's not correct logically.


>At force dependent scope I mean to check the scope in createComponent, and throw an exception for other scopes. This way it is really different, and really dumb, but does not force CDI to ignore contexts.

Alright. Now I get it. I disagree with this approach. As I said: this functionality has to have `create`  semantic.

In most usecases you are using some pre-built component (like `Dialog`) in your template.
And this logic should create a `Dialog` and not try to search for an existing bean inside a scope (which may even may have another class).

Alright, I will try to see how to create a non-contextual instance.
Thanks a lot for the info !

**Closed** 2019-05-02 07:19 UTC
