### ISSUE TITLE
Out-of-scope components are not removed from DOM

### ISSUE THREAD

**Issue by roeltje25** [vaadin/cdi#345] opened 2020-06-11 10:29 UTC
This issue is an extension request in follow-up of issue #324 . 
We noticed that an @RouteScoped component with @Route annotation which was attached to a @UIScoped layout, which itself was attached to another parent layout, was not removed when navigating to another view. We found this unintuitive as this @RouteScoped component was out of scope and should not have existed anymore. 

In issue #324 it became clear that this nonetheless is considered expected behavior. As such I would propose to change the behavior to make Out-of-scope components automatically detach from the DOM (and perhaps the state tree as well?). To this purpose I have a potential working solution which can be viewed in pull request: #344 .

With this extension / fix, no explicit care needs to be taken to add @RouteScopeOwner annotations where @RouteScoped components are clearly not owned by another component than the component itself. If a RouteScopeOwner is added (e.g. the UIScoped parentlayout comes to mind) one might even get the unwanted result that the RouteScoped component is not discarded as it may need to.

**Comment by mshabarov** [comment] 2021-05-05 11:49
Flow team is currently revisiting `@RouteScored` related enhancements and bugs in CDI and Spring add-ons.
Within this ongoing work, I was looking into this issue and able to reproduce it with the following example project based on CDI skeleton starter:

[cdi-components-retained.zip](https://github.com/vaadin/cdi/files/6426739/cdi-components-retained.zip)

1. Download the example and `mvn clean package tomee:run`
2. Go to http://localhost:8080/one-view
3. Click on `Navigate to another view` button
4. Click on `Navigate to one view` button
5. Notice the old `OneView` route component is retained inside `SubLayout`.
6. If you change
```java
@Route(value = "another-view", layout = AnotherLayout.class)
```
to
```java
@Route(value = "another-view", layout = SubLayout.class)
```
then navigating between `OneView` and `AnotherView` do not retain old components inside `SubLayout`.
Adding the `@RouteScope` annotation 

This should be qualified more like a bug, because those two cases with another view inside/outside of parent route layout hierarchy should behave similarly with no left over components.

It needs to be fixed on the flow side, or at least be documented and provide an example how to override `RouterLayout::showRouterLayoutContent` to avoid such an issues.

**Closed** 2021-05-17 11:42 UTC
Labels: Impact: Low, Severity: Major, bug
