### ISSUE TITLE
Regression in Vaadin 13: deploying multiple WARs in a single EAR to Wildfly fails

### ISSUE THREAD

**Issue by mrts** [vaadin/cdi#283] opened 2019-03-11 20:01 UTC
Deploying multiple WARs in a single EAR to WildFly 15 succeeds with Vaadin 12, but fails with Vaadin 13.

Steps to reproduce:

1. Clone the project https://gitlab.com/mrts/vaadin12-javaee-multiple-wars-in-one-ear
1. Build the EAR with `mvn package` **using JDK 11** and deploy to WildFly 15 (WildFly 14 or 16 and Java 8 will probably work equally well)
1. Verify that deployment succeeds and the application works, open http://localhost:8080/webapp1 and http://localhost:8080/webapp2
1. Checkout branch `1-migrate-to-vaadin-13` that changes Vaadin version from 12 to 13 (see the [diff here](https://gitlab.com/mrts/vaadin12-javaee-multiple-wars-in-one-ear/merge_requests/1/diffs))
1. Build the EAR with `mvn clean package` and deploy to WildFly 15
1. The deployment fails with the following error:
```
[2019-03-11 09:52:03,769] Artifact ear:ear: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ear.ear\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001318: Cannot resolve an ambiguous dependency between: 
  - Managed Bean [class com.vaadin.cdi.context.VaadinServiceScopedContext$ContextualStorageManager] with qualifiers [@Any @Default],
  - Managed Bean [class com.vaadin.cdi.context.VaadinServiceScopedContext$ContextualStorageManager] with qualifiers [@Any @Default]
```

**Comment by mrts** [comment] 2019-03-11 20:19
Can I contribute a regression test for this to avoid it in the future?

**Comment by denis-anisimov** [comment] 2019-03-12 08:39
>Can I contribute a regression test for this to avoid it in the future?

Sure. You are very welcome.

**Comment by kumm** [comment] 2019-03-24 19:08
I found it is not related to vaadin version.
On your master branch ( vaadin12) you define different version of vaadin-cdi in webapp1, and webapp2.
Just remove the version, it is managed by bom - like on the vaadin13 branch -.
After that it fails with vaadin12 too.

But with `<java.version>8</java.version>` in root pom it runs. 
It seems to be a bug in weld with java11.

**Comment by mehdi-vaadin** [comment] 2020-01-27 13:25
Since neither Vaadin 12 nor Vaadin 13 is supported anymore, would you please verify if this bug can be reproduced in Vaadin 14?

**Comment by mehdi-vaadin** [comment] 2020-02-21 09:03
It seems to me that [@kumm 's comment](https://github.com/vaadin/cdi/issues/283#issuecomment-475989773) was the solution. So, I'm closing this issue.

**Closed by mehdi-vaadin** 2020-02-21 09:03 UTC
Labels: bug, waiting for author
